### ISSUE TITLE
Does not work on heroku

### ISSUE THREAD

**Issue by mrclmrvn** [bronson/error_page_assets#3] opened 2016-10-16 02:06 UTC
Rails 5.0.0.1
Ruby 2.2.2

**Comment by bronson** [comment] 2016-10-16 05:35
What's the issue?  The files aren't generated, or they aren't being served properly?

Is it caused by Heroku's ephemeral filesystem?

**Comment by bronson** [comment] 2017-09-23 00:15
Closing, unable to reproduce.

**Closed by bronson** 2017-09-23 00:15 UTC
